CREATE DATABASE MinimalAPI_DB

USE MinimalAPI_DB

CREATE TABLE Persons (
    IDPerson INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Last_name NVARCHAR(100) NOT NULL,
    CURP NVARCHAR(18) NOT NULL
)


ALTER TABLE Persons
ADD CONSTRAINT UQ_Persons_CURP UNIQUE (CURP)

CREATE PROCEDURE SP_GetAllPersons
AS
BEGIN
    SET NOCOUNT ON;

    SELECT * 
    FROM Persons;
END

