@MinimalAPI_CRUD_HostAddress = http://localhost:5135

GET {{MinimalAPI_CRUD_HostAddress}}/persons/
Accept: application/json

###

POST {{MinimalAPI_CRUD_HostAddress}}/persons/
Content-Type: application/json

{
    "Name": "Frenando",
    "Last_name": "Flores",
    "CURP" : "FOS12HCLLNSSA2"
}

###

GET {{MinimalAPI_CRUD_HostAddress}}/persons/2
Accept: application/json

###

PUT {{MinimalAPI_CRUD_HostAddress}}/persons/2
Content-Type: application/json

{
    "IDPerson": 2,
    "Name": "Fernando",
    "Last_name": "Flores",
    "CURP" : "FOS12HCLLNSSA2"
}

###

DELETE {{MinimalAPI_CRUD_HostAddress}}/persons/2
Accept: application/json
